### ISSUE TITLE
[QUESTION] scaleing MFU calculate

### ISSUE THREAD

**Issue by ltm920716** [NVIDIA/Megatron-LM#1276]
**Your question**
Hello，
the MFU in the table is almost 40%，and the teraflops is around 400，like bellow：
https://github.com/NVIDIA/Megatron-LM?tab=readme-ov-file#training-speed-and-scalability

that is this table use fp32 float？but there is all --fp16 as param in the training script，if use fp16，the MFU should be 400 / 2000 = 20%， not 40%？

I am so confused， help please，thanks！

**Comment by plegresl** [comment]
For H100 SXM and 16-bit floating point (either fp16 or bfloat16) the theoretical peak is 1979 TFLOPS when using 2:4 structured sparsity and 989 TFLOPS when not using sparsity. Since Megatron-LM doesn't use the 2:4 structured sparsity feature, the denominator for the calculations in that table is 989 TFLOPS.
