### ISSUE TITLE
[Question]: Anyone help explain what it's for _EMBEDDING_GROUP?

### ISSUE THREAD

**Issue by starkhu** [NVIDIA/Megatron-LM#299]
In my opinion, only the first stage  is required to embed the input , other stages are not required to implement the embedding operation. therefore, the weights corresponding to the embedding are not required in other stages. Why is the weight for Embeding initialized at each stage in the code?

**Comment by yupei-ms** [comment]
I would like to understand this as well. From what I gathered via comments in 

https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/module.py#L50
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/optimizer/optimizer.py#L202

This is some type of optimizations to make the pipeline parallelism more efficient. But obviously would like to hear more.

**Comment by deepakn94** [comment]
Embeddings are initialized on at most two stages: the first and last stage. We need embeddings on the last stage in order to transform token representations from "feature space" back to "vocabulary space". If we want to keep these embeddings "tied" (i.e., when [`--untie-embeddings-and-output-weights`](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/arguments.py#L598) is not specified), we need to all-reduce the gradients to ensure the two embedding copies continue to remain in sync. Note that when not using pipeline parallelism, embeddings are tied by default.
