### ISSUE TITLE
deleted megatron-lm packages on pypi

### ISSUE THREAD

**Issue by loadams** [NVIDIA/Megatron-LM#329]
It appears that the megatron-lm packages that used to exist on [pypi were removed](https://pypi.org/project/megatron-lm/).  Now they're been replaced with two packages, 2.2.2 that seems to be a replacement for 1.1.5 which is useful, but the package doesn't appear to contain anything, so we cannot use it as a replacement for 1.1.5

**Comment by pattyler** [comment]
This also causes a build issue for us.

Our project uses Nvidia NeMo v1.3.0, [which depends on megatron-lm 2.2.0](https://github.com/NVIDIA/NeMo/blob/6d260c96015ce51eb3f4a536f82235c329034746/requirements/requirements_nlp.txt#L10). The obvious solution in this case would be for us to update the NeMo library to a more recent version that seems to remove the megatron-lm dependency, but doing so is non-trivial for us due to a mish-mash of version requirements.

**Comment by loadams** [comment]
@pattyler - depending on your version, you may be able to use the git tag 2.2.0 in your requirements.txt, but I'm still not sure why they pulled these packages.

**Comment by loadams** [comment]
It might be stale but this is still a problem for existing megatron users.

**Comment by jon-barker** [comment]
Looking into it.

**Comment by jon-barker** [comment]
The megatron-lm pypi packages were for versions of megatron-lm over two years old. NeMO has since switched to using the megatron-core pypi package. The old packages were removed from pypi to prevent confusion between megtron-lm and megatron-core packages. 

If you need to use an old version of NeMO and/or megatron-lm you can pull an old megatron-lm commit and build from source. Let me know if you need help doing that.

**Comment by loadams** [comment]
Hi @jon-barker - thanks so much for your reply and that makes sense for why the packages were pulled.  I can do that, but I'm not sure what commit the 1.1.5 package was built from.  If you know, could you share that here?

**Comment by jon-barker** [comment]
@loadams Thanks for understanding. I'm trying to track down that git commit ID for you...

**Comment by jon-barker** [comment]
@loadams I believe this is the commit you want for pip 1.1.5: https://github.com/NVIDIA/Megatron-LM/commit/d80433e1a0dd78a3bfd70e7e72d51d90169139fc

**Comment by loadams** [comment]
Thanks, I'll give that a try

**Comment by sytelus** [comment]
Hi @jon-barker, I am curious what was the reason for change in packaging strategy for megatron-lm. It seems 4 years ago all of `megatron` directory was a package but then in Sep 2022, some of the code was moves to sub-directory `core` and only `core` was made a package. Also, NeMO docker doesn't do `pip install` but modifies `PYTHONPATH`. Any idea what were the reasons?
