### ISSUE TITLE
Does the `--dataset-impl` in Pre-training support `lazy` mode? 

### ISSUE THREAD

**Issue by KB-Ding** [NVIDIA/Megatron-LM#387]
Taking the pre-training of GPT as an example, can `--dataset-impl` in [pretrain_gpt.sh](https://github.com/NVIDIA/Megatron-LM/blob/main/examples/pretrain_gpt.sh#L35) be set to `lazy`? The [GPTDataset](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/data/gpt_dataset.py#L284) uses `self.indexed_dataset.get()`, but the [IndexedDataset](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/data/indexed_dataset.py#L127) does not support the get().

**Comment by jon-barker** [comment]
No, we actually only support `--dataset-impl mmap` right now. The `lazy` and `cached` options were inherited from fairseq but are not supported in Megatron-LM. There will be an update to Megatron-LM that removes them as options for the argument and removes mention of them from the README.md.

Is there a reason you need to use `lazy` instead of `mmap`?

**Comment by KB-Ding** [comment]
@jon-barker Thanks, I wanted to try out the `lazy` mode as I saw it in README and args. Removing it will make it clear that Megatron-LM does not support this configuration.
