### ISSUE TITLE
Revert to datatype order

### ISSUE THREAD

**Issue by mayank31398** [NVIDIA/Megatron-LM#425]
@jon-barker @jaredcasper 
The ordering of dtypes has changed here: https://github.com/bigcode-project/Megatron-LM/commit/bf5206e06608d4457bf2d0d111ac7910aa22b774

eariler, 6 corresponded to 4 byte float and 7 to 8 byte float.
Does this matter?

**Comment by jon-barker** [comment]
This change was intentional. Please see the discussion here: https://github.com/NVIDIA/Megatron-LM/pull/327#issuecomment-1545870657

There was a long standing bug in Megatron-LM where np.float was incorrectly used to represent fp32 (when it actually meant fp64). Swapping the ordering was required for backwards compatibility with datasets created using the old buggy version.

Has this caused a problem for you?

**Comment by mayank31398** [comment]
Hey @jon-barker I am not using any old datasets.
So, for me the reverse order should be fine right?
I had fixed this myself in [this](https://github.com/bigcode-project/Megatron-LM/commit/bf5206e06608d4457bf2d0d111ac7910aa22b774). But this is different order of what is in Nvidia megatron.

**Comment by jon-barker** [comment]
I think either order will work for you. You might want to use the same as we are using just to stay in sync. I'll close the issue now, feel free to re-open if you hit problems. Thanks.

**Comment by mayank31398** [comment]
Thanks a lot. Unfortunately, we have created some datasets already with our current repo and it will be hard for us to do it all over again.
Ill take a look into this. Thanks
