### ISSUE TITLE
Question Regarding Throughput(Training Sequences per second)

### ISSUE THREAD

**Issue by Druva24** [NVIDIA/Megatron-LM#541]
Hi, We are using Megatron-LM source code for running benchmarking experiments of BERT-Large and GPT-2 pre-training on H100s. However in the script, there is no calculation of throughput, so can we calculate the throughput as global_batch_size/consumed_samples_per_iteration
Reference code: 
https://github.com/NVIDIA/Megatron-LM/blob/79a9feef261352ac1ee80b36f2cf73c20f864965/megatron/training.py#L609
https://github.com/NVIDIA/Megatron-LM/blob/79a9feef261352ac1ee80b36f2cf73c20f864965/megatron/training.py#L611

Thank you

**Comment by deepakn94** [comment]
global_batch_size / iteration_time will give you the throughput in sequences / second. Is that what you want?

If you want throughput in "floating point operations / second", then the numerator should be the number of floating-point operations in an iteration instead of the global batch size. https://arxiv.org/pdf/2104.04473.pdf has some details on the right formula to use for this.

**Comment by Druva24** [comment]
yes @deepakn94 , I want throughput in sequences / second

**Comment by deepakn94** [comment]
Ok, then global_batch_size / iteration_time should be good. Closing this.
