### ISSUE TITLE
Unintended error caused by compiling fused_kernels

### ISSUE THREAD

**Issue by wade3han** [NVIDIA/Megatron-LM#63]
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/arguments.py#L186-L198
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/fused_kernels/__init__.py#L46-L72

When I tried to train GPT-3 on multi-node using `torch.distributed.launch`, sometimes the training process was stuck while compiling the fused_kernels.
This bug can be occurred by timing issue when multiple processes compile concurrently.
The simplest way is to remove `./fused_kernels/build` and run script again, but I thought it is not solving the fundamental problem.

In my case, I resolved this issue can be solved by using `torch.distributed.barrier`, letting the process compile the `fused_kernels` only on master rank (rank == 0).
If the authors think resolving this issue is necessary for the codes, then I will leave PR :)

**Comment by jaredcasper** [comment]
We've had reports of this happening internally as well. The problem with only compiling on the master rank is we need to support the use case that the code lives locally on several nodes (i.e. a multinode environment and the code isn't on a shared disk). So the kernels need to be compiled on several ranks. 

`torch.utils.cpp_extension.load` is supposed to lock the directory so that only one rank runs the build at a time (and only the first run actually does anything, subsequent runs just see that it is already built and returns). Apparently that lock isn't properly deleted/released in some instances.

**Comment by wade3han** [comment]
Thanks for your response! I'm glad that your group already had reports of this happening.
Is your group internally planning to resolve this issue?

**Comment by jaredcasper** [comment]
It's on the list but pretty low priority since we seldom run into it. If you can figure out why the lock mechanism in `torch.utils.cpp_extension.load` doesn't always work as I think it should I'm all ears. :) Might be we are expecting more from it than it is meant to handle, might be we are using it wrong, might be a bug in torch, etc.

**Comment by wade3han** [comment]
I will close this issue, and if there is an additional issue then I will re-open it. Thank you :)
