### ISSUE TITLE
[QUESTION] Why `--overlap-param-gather` is supported only with mcore models?

### ISSUE THREAD

**Issue by Ktakuya332C** [NVIDIA/Megatron-LM#728]
I recently noticed that the `--overlap-param-gather` option is explicitly disabled when training models without mcore. I found the commit introduced the restriction ( daf0006 ), but cannot understand why this is necessary. As far as I can understand, the changes around that commit was innocuous to the `--overlap-param-gather` option, and I could not find any particular bug or inconvenience this option might introduce. 

If someone knows a likely reason behind the change, I would appreciate if you leave a comment.

( By the way, thank you for sharing this great repository !  )

**Comment by deepakn94** [comment]
Good question.

The commit you linked to fixes a bug where we had a mis-match in how tied embeddings were laid out in buckets when PP > 1. The fix was to ensure that embedding parameters reside in their own separate buckets. However, the param-gather overlap code relies on PyTorch pre-hooks to mark synchronization points for the all-gather: these don't work for parameters that aren't wrapped in a PyTorch module. For non-MCore models, the embedding copy in the head is not in a PyTorch module, so we will see hangs if the embedding is in its own bucket (a pre-hook won't be able to tell us when to synchronize on a communication handle). This is the reason I put in this assertion.

We are going to deprecate the non-MCore model implementations eventually, so we felt it wasn't a good use of time to fix the non-MCore model.

**Comment by Ktakuya332C** [comment]
Thank you for your comment ! I now understands the reason behind the change. 

> For non-MCore models, the embedding copy in the head is not in a PyTorch module, so we will see hangs if the embedding is in its own bucket (a pre-hook won't be able to tell us when to synchronize on a communication handle).

I was unable to reproduce the hang (not sure why), but was able to observe that the parameters of the head does not get updated when using `--overlap-param-gather` on non-mcore models.

> We are going to deprecate the non-MCore model implementations eventually, so we felt it wasn't a good use of time to fix the non-MCore model.

This issue motivates me to move on to mcore version of the codebase. Thank you for pointing me out.
