### ISSUE TITLE
[QUESTION] why pipeline-model-parallel size should be greater than 2 with interleaved schedule ？

### ISSUE THREAD

**Issue by nullnonenilNULL** [NVIDIA/Megatron-LM#750]
**Your question**
Ask a clear and concise question about Megatron-LM.

![image](https://github.com/NVIDIA/Megatron-LM/assets/34435196/33f48852-3cc4-4464-b0e2-02e468b9ec12)

**Comment by ethanhe42** [comment]
You can't use interleaved schedule without pipeline parallel
![image](https://github.com/NVIDIA/Megatron-LM/assets/10027339/6e945b62-4a23-4779-829a-fe36c01c47ff)

**Comment by yuantailing** [comment]
@ethanhe42 I wonder whether `pipeline_model_parallel_size == 2` can be accepted?

**Comment by nullnonenilNULL** [comment]
> @ethanhe42 I wonder whether `pipeline_model_parallel_size == 2` can be accepted?

@ethanhe42 same question.

**Comment by robotsp** [comment]
I think that pipeline_model_parallel_size == 2 can be accepted in practice but maybe with less or no benefits in reducing bubble ?

**Comment by deepakn94** [comment]
It is because `tensor_send_next` and `tensor_send_prev` here are indistinguishable with PP=2: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/pipeline_parallel/p2p_communication.py#L586.

This is a non-issue with `overlap_p2p_comm` since we split forward and backward communication in steady state. We fixed this here: https://github.com/NVIDIA/Megatron-LM/commit/152c562067cc0de6cbc8fba2a5095208f30d10cd.

Going to mark this as closed, feel free to re-open if you have additional questions.
